name: matcha-dev

services:
  fastify:
    container_name: fastify-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      PG: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGDB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: db
      PGPORT: 5432
      RUN_SEED: ${RUN_SEED}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
      IPSTACK_API_KEY: ${IPSTACK_API_KEY}
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      DOMAIN: matcha.fr
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      FT_CLIENT_ID: ${FT_CLIENT_ID}
      FT_CLIENT_SECRET: ${FT_CLIENT_SECRET}
    restart: on-failure
    build: 
        context: ./fastify
        args:
          NODE_ENV: dev
    expose:
      - 3000
    networks:
      - router
    develop:
      watch:
        - action: sync
          path: ./fastify/assets
          target: /usr/src/app
          ignore:
            - node_modules/
            - uploads/
  
  nextjs:
    container_name: nextjs-app
    depends_on:
      fastify:
        condition: service_healthy
    environment:
      NODE_ENV: dev
      NEXT_PUBLIC_API_URL: https://matcha.fr/api
      NEXT_PUBLIC_WS_URL: wss://matcha.fr/socket.io
    restart: on-failure
    build: 
        context: ./nextjs
        args:
          NODE_ENV: dev
    expose:
      - 3000
    networks:
      - router
    develop:
      watch:
        - action: sync
          path: ./nextjs/matcha
          target: /usr/src/app
          ignore:
            - node_modules/
            - .next/

  nginx:
    container_name: nginx
    depends_on:
      fastify:
        condition: service_healthy
      nextjs:
        condition: service_started
    restart: on-failure
    build:
        context: ./nginx
    ports:
        - 443:443
        - 80:80
    networks:
      - router

  db:
    image: postgres:18-alpine3.22
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - pgdata:/var/lib/postgresql/data
     - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - router
    ports:
      - 5432:5432

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:5.4.1
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - router

volumes:
  pgdata:
    driver: local

networks:
  router:
    driver: bridge
