name: matcha-test

services:
  fastify:
    container_name: fastify-app
    depends_on:
      - db
    environment:
      NODE_ENV: test
      PG: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGDB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGHOST: db
      PGPORT: 5432
      RUN_SEED: ${RUN_SEED}
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_SECRET: ${COOKIE_SECRET}
    build: 
        context: ./fastify
        args:
          NODE_ENV: test
    expose:
      - 3000
    networks:
      - router
    develop:
      watch:
        - action: sync
          path: ./fastify/assets
          target: /usr/src/app
          ignore:
            - node_modules/

  db:
    image: postgres:18-alpine3.22
    logging:
      driver: "none"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
     - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - router
    ports:
      - 5432:5432


networks:
  router:
    driver: bridge
