name: Run app test docker compose
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run fastify app tests
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          IPSTACK_API_KEY: ${{ secrets.IPSTACK_API_KEY }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          POSTGRES_USER: random_user
          POSTGRES_PASSWORD: random_password
          POSTGRES_DB: matcha_db
          RUN_SEED: true
          JWT_SECRET: jwt_secret
          COOKIE_SECRET: cookie_secret
        run: docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from fastify
